// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPRmdTkdBn__ib3aDN4Myo8bg9quNfhNA',
    appId: '1:443050369009:web:c129476fdab21205ccee50',
    messagingSenderId: '443050369009',
    projectId: 'database-f3419',
    authDomain: 'database-f3419.firebaseapp.com',
    storageBucket: 'database-f3419.appspot.com',
    measurementId: 'G-FRQ1CD1WRD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa4HCaLU3XJ1_n8eCLY8cQsjmf-0N92rI',
    appId: '1:443050369009:android:f0062fd58ef51965ccee50',
    messagingSenderId: '443050369009',
    projectId: 'database-f3419',
    storageBucket: 'database-f3419.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEzSgQO5KJeu_ejPVX39FZWRbEJ_yHrtQ',
    appId: '1:443050369009:ios:c8a8dff0974c17ebccee50',
    messagingSenderId: '443050369009',
    projectId: 'database-f3419',
    storageBucket: 'database-f3419.appspot.com',
    iosClientId: '443050369009-svkkm1g0hemcdll8ms041enlfp4difh6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEzSgQO5KJeu_ejPVX39FZWRbEJ_yHrtQ',
    appId: '1:443050369009:ios:c8a8dff0974c17ebccee50',
    messagingSenderId: '443050369009',
    projectId: 'database-f3419',
    storageBucket: 'database-f3419.appspot.com',
    iosClientId: '443050369009-svkkm1g0hemcdll8ms041enlfp4difh6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2',
  );
}
